server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/myNTQdb
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
secret-key: "admin"
